/**
 * Created by ekersale on 30/11/2016.
 */

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'Who am I'          : 'Who am I',
  'Find me'           : 'Find me',
  'Career'            : 'Career',
  'Skills'            : 'Skills',
  'My'                : 'My',
  'Me'                : 'Me',
  'Achievements'      : 'Achievements',
  'Education'         : 'Education',
  'Contact me'        : 'Contact me',
  'Dev'               : 'Developer',
  'Co founder'        : 'Co-fondateur',
  'jobName'           : 'Fullstack developer',
  'LifeDetails'       : "I'm born at the computers beginning. As far I can remember I always grown up with that new technologies. For that reason I developed the ability to understand and learn quickly. Later when the choice came I engage myself in computer science. Starting by software engineering I moved to web engineering which presents significant benefits.",
  "What am I looking for ?":"What am I looking for",
  'WhatIWantDetails'  : "I am keen to begin a career in web and software engineering. I’m looking for a position in web application development out of France. During my previous experience I have shown myself to be self-motivated and autonomous for achieving my goals.",
  'Frontend'          : 'Front end',
  'System'            : 'System',
  'Tools'             : 'Tools',
  'Backend'           : 'Back end',
  'month'             : 'month',
  'Company'           : 'Company',
  'Sogeti Job Details': '',
  'BeaVR Job Details' : '',
  'Thales Job Details': "",
  'etesting Job Details': "",
  'This is a required field.': 'This is a required field.',
  'Get in touch!'     : 'Get in touch!',
  'Email address'     :'Email address',
  'Subject'           :'Subject',
  'Web development'   : 'Web development',
  'years'             :  'years',
  'Standalone app'    : 'Standalone app',
  'System admin'      : 'System admin',
  'Curiosity'         : 'Curiosity',
  'Team work'         : 'Team work',
  'Agile methods'     : 'Agile methods',
  'Languages'         : 'Languages',
  'French'            : 'French',
  'English'           : 'English',
  'Creator explanation'     : 'The « Creator » project is part of BeaVR ecosystem. This tool wants to allow people without development skills to create 3D scenes in their browser. More over it’s our way to demonstrate that it’s possible to make 3D applications in the web browser, indeed we believe that it’s a necessary step toward the democratization of virtual reality.\n\nDeveloped from May-2016 to January-2017.',
  'Store explanation'       : 'The « Store » project is part of BeaVR ecosystem. This tool is the market place of our ecosystem. It allows users to put, exchange and sell their applications created from the   « Creator ».\n\nDeveloped from May-2016 to January-2017.',
  'Vitrine explanation'     : 'This project is BeaVR ecosystem portal aiming to redirect to the « Store » and « Creator ». It also allows BeaVR team to communicate about their progression.\n\nDeveloped in October-2016.',
  'CV explanation'          : '',
  'SafetyCheck explanation' : '',
  'GithubAPI explanation'   : '',
  'UMovie explanation'      : '',
  'MyIRC explanation'       : '',
  'Nibbler explanation'     : ''
};
